config/routes.rb
Rails.application.routes.draw do
resources :users
resources :sessions
resources :details
resources :guests
resources :admins
resources :accesses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ActiveRecord::Base
has_secure_password
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	  has_one :detail
	  attr_accessor :password

  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email,password)
 	user= find_by_email(email)
 	if user&&user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
  		
        user
     else
     	nil
     end
 end


   def encrypt_password
  		if password.present?
  		self.password_salt=BCrypt::Engine.generate_salt
  		self.password_hash=BCrypt::Engine.hash_secret(password,password_salt)
		end
	end

end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
	def index
		@accesses=Detail.all
	end

	 def edit
  	@access = Detail.find(params[:id])
  end

  def update
  	@access = Detail.find(params[:id])
 
    if @access.update(detail_params)
      redirect_to accesses_path
    else
      render 'edit'
    end
  end

   protected
  def detail_params
  	params.require(:detail).permit(:id,:firstname,:lastname,:age,:salary,:location)
  end
	
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def new

	end
	 def create
    admin= Admin.find_by_username(params[:username])
    if admin && admin.authenticate(params[:password])
    	session[:username_id] = admin.id
      redirect_to accesses_path
    else
    	render 'admins/new'
    end
  end

  def destroy
    session[:username_id] = nil
    redirect_to root_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
helper_method :admin_user


private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

private

def admin_user
  @current_user ||= Admin.find(session[:username_id]) if session[:username_id]
end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
def new
  	@detail= Detail.new
    end
def create

  	@user=current_user
  	params.permit!
  	@detail = current_user.build_detail(params[:detail])
  	if @detail.save
     redirect_to '/details/show'

    else
      render 'new'
    end
  end 
 def show
  	
    @detai= current_user
  end

  def edit
@detail =current_user.detail(params[:id])
  end

  def update
@detail = current_user.detail(params[:id])
    if @detail.update(detail_params)
      redirect_to '/details/show'
    else
      render 'edit'
    end
  end

  protected
  def detail_params
  	params.require(:detail).permit(:id,:firstname,:lastname,:age,:salary,:location)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
	 end
	 def create
      user=User.authenticate(params[:email],params[:password])
          if user
          	session[:user_id]=user.id
          	if current_user.detail.blank?

          	redirect_to '/details/new'
          else
			redirect_to '/details/show'
		end
          else
          	flash.now.alert ="Invalid"
          	render 'http://www.google.com'
          end
     end
     def destroy
	 session[:user_id]= nil
	 redirect_to "http://www.amazon.co.in", :notice=> "logged out"
     end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
 
@user=User.new
end
def create
  	params.permit!
 @user =User.new(params[:user])
 	if @user.save
 		redirect_to '/sessions/new', :notice=>"signed up"
	else
		render "new"
	end

  end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accesses/edit.html.erb
<%= form_for @access , url: access_path(@access), method: :patch do |f| %>


  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %><br/>
  </p>
  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %><br/>
  </p>
  <p>
    <%= f.label :age %><br>
    <%= f.text_field :age %><br/>
  </p>
    <p>
    <%= f.label :salary %><br>
    <%= f.text_field :salary %><br/>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_area :location %><br/>
  </p>
 
  <p>
    <%= f.submit "save" %>
  </p>
<% end %>

app/views/accesses/index.html.erb
<% Detail.all.each do |acc| %><br>
First name: <%= acc.firstname %><br>
Lastname: <%= acc.lastname %><br>
Location: <%= acc.location %><br>
Salary: <%= acc.salary %><br>
<%= link_to 'edit',edit_access_path(acc) %>
<hr>
<% end %>

app/views/admins/new.html.erb
<h1>Login</h1>

<%= form_tag admins_path do %>

  username: <%= text_field_tag :username %><br><br>
  Password: <%= password_field_tag :password %><br><br>
  <%= submit_tag "Submit" %><br>

<% end %>

app/views/details/edit.html.erb
<%= form_for @detail ,url: detail_path(@detail),  method: :patch do |f| %>


  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %><br/>
  </p>
  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %><br/>
  </p>
  <p>
    <%= f.label :age %><br>
    <%= f.text_field :age %><br/>
  </p>
    <p>
    <%= f.label :salary %><br>
    <%= f.text_field :salary %><br/>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_area :location %><br/>
  </p>
 
  <p>
    <%= f.submit "save" %>
  </p>
<% end %>

app/views/details/new.html.erb
<%= form_for @detail do |f| %>
  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %><br/>
  </p>
  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %><br/>
  </p>
   <p>
    <%= f.label :age %><br>
    <%= f.text_field :age%><br/>
  </p>
  
  <p>
    <%= f.label :salary %><br>
    <%= f.text_field :salary %><br/>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_area :location %><br/>
  </p>
  <p>
    <%= f.submit "save" %>
  </p>
<% end %>


<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>Column heading</th>
      <th>Column heading</th>
      <th>Column heading</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="info">
      <td>3</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="success">
      <td>4</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="danger">
      <td>5</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="warning">
      <td>6</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
    <tr class="active">
      <td>7</td>
      <td>Column content</td>
      <td>Column content</td>
      <td>Column content</td>
    </tr>
  </tbody>
</table> 

app/views/details/show.html.erb
<p>
  <strong>Firstname:</strong>
  <%= @detai.detail.firstname %>
</p>
<p>
  <strong>lastname:</strong>
  <%= @detai.detail.lastname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @detai.detail.age %>
</p>
<p>
  <strong>salary:</strong>
  <%= @detai.detail.salary %>
</p>
<p>
  <strong>Location:</strong>
  <%= @detai.detail.location %>
</p>
<%= link_to "edit" ,'details/edit' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boss</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
   <%= render 'shared/navbar' %>

   
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<h1> signup</h1>
<%= form_for @user do |f| %>
<p><%= f.label :email %><br>
<%= f.text_field :email %></p>

<p><%=f.label :password %><br>
<%= f.password_field :password %> </p>
<p><%=f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation %></p>
<%= f.submit "create" %>
<% end %>